baseurl = "/"
languageCode = "en-us"
theme = "hugo-paper"
paginate = 5
# DisqusShortname = ''
# googleAnalytics = "UA-123-45"
enableEmoji = true

[params]
  author="Saurabh Sharma"

[languages]
  [languages.en]
    title = "Saurabh Sharma"
    subtitle = "My place on this internet"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"